name: build-node

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: NPM 10 on ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - name: Monitor action permissions.
        if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: Checkout.
        uses: actions/checkout@v5

      - name: Install dependencies.
        run: composer update $DEFAULT_COMPOSER_FLAGS

      - name: Install node.js.
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Tests.
        run: |
          npm install
          npm test
