name: Outdated links in repository files
permissions:
  contents: read|write
on:
  push:
    branches:
      - master
  schedule:
    # Run every week at 2:00
    - cron: '0 2 */7 * *'
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Display and fix outdated links
        shell: bash
        # Run `FixLinksController::actionIndex()`, safe mode: off
        run: './build/build fix-links'
